name: CI

on: [push, pull_request]

jobs:
  build:
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - windows-latest
          - macos-13
      fail-fast: false
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "lts/*"
      - uses: pxshadow/setup-hashlink@v1.0.4
      - name: Install lix
        run: npm i lix -g
      - name: Download Haxe and library dependencies
        run: npx lix download
      - name: Build test suite
        run: npx haxe tests.hxml
      - name: Run test suite for Hashlink target
        run: hl test.hl
      - name: Install Node.js dependencies
        run: npm add deasync
      - name: Run test suite for Node.js target
        run: node test.js
